"""add language to posts

Revision ID: 322fd09b0287
Revises: ff8577d4fc14
Create Date: 2020-04-02 14:33:20.361835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322fd09b0287'
down_revision = 'ff8577d4fc14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
